### ISSUE TITLE
Getting error Error: You must provide a path for a model definition when using @upscalerjs/esrgan-slim/2x

### ISSUE THREAD

**Issue by deepushajia** [thekevinscott/UpscalerJS#1295]
**Describe the bug**
utils.js:17 Uncaught (in promise) Error: You must provide a path for a model definition
    at ./node_modules/upscaler/dist/browser/esm/utils.js (utils.js:17:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:22:1)
    at fn (hot module replacement:61:1)
    at ./node_modules/upscaler/dist/browser/esm/loadModel.generated.js (index.js:3:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:22:1)
    at fn (hot module replacement:61:1)
    at ./node_modules/upscaler/dist/browser/esm/upscaler.js (upscale.js:258:1)
    at options.factory (react refresh:6:1)
    
    @ 
    
    const upscaler =  new Upscaler({
    model: x2
  })

**Expected behavior**
Model should be loaded as described in the documentation

**Additional context**

**Comment by ambient-labs** [comment]
Hi @deepushajia , can you provide your full code (particularly the import statement)? Or provide a code sandbox that reproduces the issue?

Also, is this in the browser or Node?

**Comment by thekevinscott** [comment]
Hi [@deepushajia](https://github.com/deepushajia) , can you provide your full code (particularly the import statement)? Or provide a code sandbox that reproduces the issue?

Also, is this in the browser or Node?

**Comment by deepushajia** [comment]
This is in a react application.

`// UpscaleImage.jsx
import React, { useState } from 'react';
import Upscaler from 'upscaler';
import x2 from '@upscalerjs/esrgan-slim/2x';

const UpscaleImage = () => {
  const [originalImage, setOriginalImage] = useState(null);
  const [upscaledImage, setUpscaledImage] = useState(null);
  const upscaler =  new Upscaler({
    model: x2
  })

  // Function to handle file input
  const handleImageUpload = (e) => {
    const file = e.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (event) => {
        setOriginalImage(event.target.result);
      };
      reader.readAsDataURL(file);
    }
  };

  // Function to upscale the image
  const upscaleImage = async () => {
    if (!originalImage) return;
    // Initialize Upscaler with the ESRGAN Slim model

    const img = new Image();
    img.src = originalImage;
    img.onload = async () => {
      const upscaled = await upscaler.upscale(img);
      setUpscaledImage(upscaled);
    };
  };

  return (
    <div className="flex flex-col items-center p-4 bg-gray-100 rounded-lg shadow-md">
      <h2 className="text-2xl font-bold mb-4">UpscalerJS with ESRGAN Slim</h2>
      <input
        type="file"
        accept="image/*"
        onChange={handleImageUpload}
        className="mb-4 p-2 border rounded"
      />
      <button
        onClick={upscaleImage}
        className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 transition"
      >
        Upscale Image
      </button>
      <div className="flex flex-col items-center mt-4">
        {originalImage && (
          <img
            src={originalImage}
            alt="Original"
            className="w-48 h-48 object-cover mb-4 rounded"
          />
        )}
        {upscaledImage && (
          <img
            src={upscaledImage}
            alt="Upscaled"
            className="w-48 h-48 object-cover rounded"
          />
        )}
      </div>
    </div>
  );
};

export default UpscaleImage;
`

**Comment by thekevinscott** [comment]
Your code seems to have gotten mangled when pasted, but I think I get the gist.

Check this out for a working integration with React:

https://codesandbox.io/p/sandbox/xenodochial-feynman-76m9k3?workspaceId=5827380d-c0eb-4489-8de0-a045510daa2d

You can drag and drop an image and specify the model during instantiation to UpscalerJS.

**Comment by thekevinscott** [comment]
Going to close, feel free to reopen if still an issue.
